name: mobipad
description: A notepad for mobile.

publish_to: 'none'

version: 1.1.3+14

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl:
  shimmer:
  font_awesome_flutter:
  email_validator:
  flutter_speed_dial:
  cloud_firestore:
  firebase_core:
  firebase_auth:
  google_sign_in:
  flutter_local_notifications:
  webview_flutter:
  flutter_redux:
  redux:
  redux_logging:
  rxdart:
  built_value:
  built_collection:
  timezone:
  package_info_plus:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  built_value_generator:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/oh-notes_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/oh-notes_logo.png
    - assets/img/note_art.png
    - assets/img/todo_art.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
    - family:  OhNotes
      fonts:
       - asset: assets/fonts/OhNotes.ttf
